version: "3"
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - /usr/src/app/node_modules
            - ./frontend:/usr/src/app
        container_name: youtube_frontend
        stdin_open: true
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - /usr/src/app/node_modules
            - ./backend:/usr/src/app
        container_name: youtube_backend
    nginx:
        restart: always
        container_name: youtube_nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "3001:80"
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
