version: "3"
services:
    redis:
        image: redis:alpine
        expose:
            - "6379"
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.frontend
        image: exit21sb/youtube-comments-manager-frontend
        container_name: youtube_frontend
        volumes:
            - /usr/src/app/node_modules
            - ./frontend:/usr/src/app
        stdin_open: true
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.backend
        image: exit21sb/youtube-comments-manager-backend
        container_name: youtube_backend
        links:
            - redis:redis
        environment:
            - REDIS_URL=redis
            - NODE_ENV=development
        env_file:
            - ./backend/.env    
        volumes:
            - /usr/src/app/node_modules
            - ./backend:/usr/src/app
    nginx:
        restart: always
        image: exit21sb/youtube-comments-manager-nginx
        container_name: youtube_nginx
        build:
            context: ./nginx
            dockerfile: ./Dockerfile.nginx
        ports:
            - "3000:80"