version: "3"
services:
    redis:
        image: redis:alpine
        expose:
            - 6379
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: youtube_frontend
        volumes:
            - /usr/src/app/node_modules
            - ./frontend:/usr/src/app
        stdin_open: true
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: youtube_backend
        links:
            - redis:redis
        environment:
            - REDIS_URL=redis
        volumes:
            - /usr/src/app/node_modules
            - ./backend:/usr/src/app
    nginx:
        restart: always
        container_name: youtube_nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "3000:80"